#!/bin/sh
sep="\n"

up=$(uptime | awk ' { print $3 " days " $5 } ' | sed 's/,//;s/:/h /;s/$/min/g');
ram=$(top -l1 | awk '/PhysMem/ { print $10 } ');
idle=$(top -l2 | awk  '/CPU usage:/ && NR > 8 { print $7 " " $8 } ');

printf "%-10s%s$sep" "Uptime" "[0;31m$up[0m"
printf "%-10s%s$sep" "RAM" "[0;31m$ram[0m"
printf "%-10s%s$sep" "CPU" "[0;31m$idle[0m"
