#!/bin/sh

up=$(uptime | awk ' { print $3 " days " $5 } ' | sed 's/,//;s/:/h /;s/$/min/g');
ram=$(top -l1 | awk '/PhysMem/ { print $8 } ');
idle=$(top -l2 | awk  '/CPU usage:/ && NR > 8 { print $7 " " $8 } ');

echo "Uptime |[0;31m $up\t\t[0mRAM |[0;31m $ram\t\t[0mCPU |[0;31m $idle[0m"
